# Site settings
title: Nini Codes
header-img: img/home-bg.png
email: nisselovendahl@gmail.com
copyright_name: nlovendahl
description: > # this means to ignore newlines until "baseurl:"
  still_learning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nlovendahl
learn_profile: nlovendahl
email_username: nisselovendahl@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
